#!/usr/bin/env perl

use utf8;
use strict;
use warnings;

use Getopt::Lucid qw( :all );
use IPC::Run qw(run);
use File::Spec;
use List::Util qw(max);

use constant
{
	EX_DATAERR  => 65,
	EX_NOINPUT  => 66,
	EX_SOFTWARE => 70,
	EX_CONFIG   => 78,

	BTRAM_BIND_BLOCK     => 80,
	BTRAM_UMOUNT_FAILED  => 81,
	BTRAM_MOUNT_FAILED   => 82,
	BTRAM_RESTORE_FAILED => 83,
	BTRAM_ROLLBACK_FAILED=> 84,
};

my @options_spec = (
	Switch(    '--run|-r')->doc('Actually perform [re]mount operations' ),
	Switch('--verbose|-v')->doc('Print analysis details'                ),
	Switch(  '--force|-f')->doc('Pass -f to umount'                     ),
	Switch(   '--help|-h')->doc('Print usage (this)'                    ),
);

my $options = Getopt::Lucid->getopt(\@options_spec, {strict => 1})->validate();

usage() and exit(0) if $options->get_help;

STDOUT->autoflush(1);
STDERR->autoflush(1);

my $mode_run     = $options->get_run();
my $mode_verbose = $options->get_verbose();
my $mode_force   = $options->get_force();

my @ignore_mount_prefixes = qw(/proc /sys /sysfs /var);

my $config = &get_config_raw('/etc/btram.conf');
my $rc = &validate_config($config);

my %is_root_mount;
for my $mountPoint (keys %$config)
{
	next unless defined $config->{$mountPoint};
	$is_root_mount{$config->{$mountPoint}->{root}} = 1;
}

our (%bd2root, %root2bd); # Map between device nodes and root-subvol mounts

open my $mountinfoHandle, '<', '/proc/self/mountinfo' or die;

# TODO check that mount points corresponding to config items have snapshots mounted that conform to config's pattern

my $mount_tree = &mt_new('/', '/');

while (<$mountinfoHandle>)
{
	next unless my $mountInfo = &parse_mountinfo($_);
	next if &is_ignored_mount_path($mountInfo->{mount});
	&mt_insert($mount_tree, $mountInfo->{mount}, $mountInfo);
}

close $mountinfoHandle;

&mt_walk($mount_tree, sub {
	my ($node) = @_;
	my $mountInfo = $node->{oldMount};
	return unless defined $mountInfo and $mountInfo->{fstype} eq 'btrfs';

	my ($blockDevice, $mountPoint, $subvol) = ($mountInfo->{blkdev}, $mountInfo->{mount}, $node->{oldSubvol});

	if (defined $subvol)
	{
		return unless $subvol eq '';
	}
	else
	{
		return unless $is_root_mount{$mountPoint};
	}

	$bd2root{$blockDevice} = $mountPoint;
	$root2bd{$mountPoint} = $blockDevice;
});

for my $mount (keys %$config)
{
	my $configEntry = $config->{$mount};
	next unless defined $configEntry;

	my $node = &mt_get_node($mount_tree, $mount, 1);
	if (defined $node)
	{
		$node->{cfg} = $configEntry;
	}
}

&mt_walk($mount_tree, sub {
	my ($node) = @_;
	return unless defined $node->{cfg};

	my $configEntry = $node->{cfg};
	my $mountInfo = $node->{oldMount};

	my $rootMount = $configEntry->{root};
	die unless defined $rootMount;

	if (defined $mountInfo)
	{
		return unless $mountInfo->{fstype} eq 'btrfs';

		my ($blockDevice, $mountPoint, $subvol) = ($mountInfo->{blkdev}, $mountInfo->{mount}, $node->{oldSubvol});
		my $subvolNew = &process_mount($blockDevice, $mountPoint, $subvol);
		$node->{newSubvol} = $subvolNew if defined $subvolNew;
	}
	else
	{
		my $subvolNew = &find_latest($rootMount, $configEntry->{dir}, $configEntry->{prefix});
		warn "Warning: '$node->{path}' has no snapshots '$configEntry->{dir}/$configEntry->{prefix}.*'\n" unless defined $subvolNew;
		$node->{newSubvol} = $subvolNew if defined $subvolNew;
		print "Mount: '$node->{path}' -> '$rootMount/$subvolNew'\n" if $mode_verbose and defined $subvolNew;
	}
});

my @swap_roots;
&mt_collect_swap_roots($mount_tree, \@swap_roots);

if (not $mode_run)
{
	$rc = max($rc, 1) if @swap_roots;
}
else
{
	for my $r (@swap_roots)
	{
		$rc = max($rc, &do_transaction($r));
	}
}

exit $rc;

################################################################################

sub usage
{
  print "BTRam v1.0, copyright © 2023 Luxagen\n\n";

  print $options->usage();

  print <<EOF

https://github.com/luxagen/btram

EOF
}

sub get_config_raw
{
	my ($file) = @_;

	my %result;

	open my $configHandle, '<', $file or do { warn "Missing/inaccessible config; nothing to do\n"; exit EX_NOINPUT; };

	while (<$configHandle>)
	{
		next if /^\n$/;
		next if /^\s*#/;


		unless (/^([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t]+)\n$/)
		{
			warn "Error: config line is malformed\n";
			exit EX_DATAERR;
		}
		unless ($1 and $2 and $3 and $4)
		{
			warn "Error: config line is missing field(s)\n";
			exit EX_DATAERR;
		}

		$result{$1}->{root  } = $2;
		$result{$1}->{dir   } = $3;
		$result{$1}->{prefix} = $4;
	}

	close $configHandle;

	return \%result;
}

sub validate_config
{
	my ($config) = @_;

	return EX_SOFTWARE unless defined $config;

	my $rc = 0;

	for my $mount (keys %$config)
	{
		my $configEntry = $config->{$mount};
		next unless defined $configEntry;

		my $root = $configEntry->{root};
		my $dir = $configEntry->{dir};
		unless (defined $root and defined $dir)
		{
			warn "Error: internal error: config missing required fields\n";
			exit EX_SOFTWARE;
		}

		if (&is_ignored_mount_path($mount))
		{
			warn "Error: subvol mount point '$mount' is under an ignored mount tree\n";
			exit EX_CONFIG;
		}
		if (&is_ignored_mount_path($root))
		{
			warn "Error: volume mount point '$root' is under an ignored mount tree\n";
			exit EX_CONFIG;
		}

		my $retryable = 0;
		if (not -e -d $mount)
		{
			warn "Warning: subvol mount point '$mount' missing\n";
			$retryable = 1;
		}
		if (not -e -d $root)
		{
			warn "Warning: volume mount point '$root' missing\n";
			$retryable = 1;
		}
		if (not -e -d "$root/$dir")
		{
			warn "Warning: snapshot directory '$root/$dir' missing\n";
			$retryable = 1;
		}

		if ($retryable)
		{
			$config->{$mount} = undef;
			$rc = max($rc, 2);
		}
	}

	return $rc;
}

sub parse_mountinfo
{
	my ($line) = @_;

	chomp $line;

	my ($left, $right) = split(/\s-\s/, $line, 2);
	return undef unless defined $right;

	my @l = split(/\s+/, $left);
	return undef unless @l >= 6;

	my ($root, $mount, $opts) = @l[3,4,5];
	$root  = &unescape_mountinfo($root);
	$mount = &unescape_mountinfo($mount);

	my @r = split(/\s+/, $right, 3);
	return undef unless @r == 3;
	my ($fstype, $source, $superopts) = @r;
	$source = &unescape_mountinfo($source);

	my $result =
	{
		blkdev => $source,
		mount => $mount,
		fstype => $fstype,
		options => {},
		mnt_opts => {},
		super_opts => {},
		root => $root,
		is_bind => 0,
		done => 0,
	};

	&parse_mount_opts($result->{mnt_opts}, $opts);
	&parse_mount_opts($result->{super_opts}, $superopts);

	%{$result->{options}} = (%{$result->{mnt_opts}}, %{$result->{super_opts}});

	$result->{is_bind} = 1 if exists $result->{mnt_opts}->{bind} or exists $result->{mnt_opts}->{rbind};

	return $result;
}

sub parse_mount_opts
{
	my ($out, $s) = @_;

	return unless defined $out and defined $s;

	for (split(/,/, $s))
	{
		next unless /^([^=]+)(?:=(.+))?$/;
		$out->{$1} = $2;
	}
}

sub unescape_mountinfo
{
	my ($s) = @_;

	return undef unless defined $s;

	$s =~ s/\\([0-7]{3})/chr(oct($1))/ge;
	return $s;
}

sub mt_new
{
	my ($name, $path) = @_;

	return
	{
		name => $name,
		path => $path,
		children => {},
	};
}

sub mt_insert
{
	my ($root, $path, $mountInfo) = @_;

	die unless defined $root and defined $path and defined $mountInfo;

	my @parts = grep { $_ ne '' } split(m{/+}, $path);

	my $node = $root;
	my $pathSoFar = '';
 
	for my $part (@parts)
	{
		$pathSoFar .= "/$part";

		my $child = $node->{children}->{$part};
		unless (defined $child)
		{
			$child = &mt_new($part, $pathSoFar);
			$node->{children}->{$part} = $child;
		}

		$node = $child;
	}

	die "Duplicate mount point '$path'\n" if defined $node->{oldMount};

	$node->{oldMount} = $mountInfo;

	my $subvol = $mountInfo->{options}->{subvol};
	$subvol = '' if defined $subvol and $subvol eq '/';
	$subvol =~ s{^/}{} if defined $subvol;
	$node->{oldSubvol} = $subvol;
}

sub mt_get_node
{
	my ($root, $path, $create) = @_;

	die unless defined $root and defined $path;

	my @parts = grep { $_ ne '' } split(m{/+}, $path);

	my $node = $root;
	my $pathSoFar = '';

	if ($create and defined $node->{oldMount} and $node->{oldMount}->{is_bind})
	{
		warn "Error: refusing to create node for '$path' under bind mount '$node->{path}'\n";
		return undef;
	}

	for my $part (@parts)
	{
		$pathSoFar .= "/$part";
		my $child = $node->{children}->{$part};
		unless (defined $child)
		{
			return undef unless $create;
			$child = &mt_new($part, $pathSoFar);
			$node->{children}->{$part} = $child;
		}
		$node = $child;

		if ($create and defined $node->{oldMount} and $node->{oldMount}->{is_bind})
		{
			warn "Error: refusing to create node for '$path' under bind mount '$node->{path}'\n";
			return undef;
		}
	}

	return $node;
}

sub mt_collect_swap_roots
{
	my ($node, $out) = @_;

	my $mountInfo = $node->{oldMount};

	my $swap = 0;
	if (defined $node->{newSubvol})
	{
		if (defined $mountInfo)
		{
			$swap = 1 if $mountInfo->{fstype} eq 'btrfs' and defined $node->{oldSubvol} and $node->{newSubvol} ne $node->{oldSubvol};
		}
		else
		{
			$swap = 1;
		}
	}

	if ($swap)
	{
		if (-e -d $node->{path})
		{
			push @$out, $node;
			return;
		}
		return;
	}

	for my $child (values %{$node->{children}})
	{
		&mt_collect_swap_roots($child, $out);
	}
}

sub do_transaction
{
	my ($nodeTXRoot) = @_;
	my $rc = 0;

	if (my $bindMountPath = &mt_find_bind_ancestor($mount_tree, $nodeTXRoot->{path}))
	{
		warn "Error: bind mount ancestor '$bindMountPath' blocks remount transaction for '$nodeTXRoot->{path}'\n";
		return BTRAM_BIND_BLOCK;
	}

	my $mountInfoTXRoot = $nodeTXRoot->{oldMount};

	if (my $bindMountPath = &tx_find_bind_descendant($nodeTXRoot))
	{
		warn "Error: bind mount descendant '$bindMountPath' blocks remount transaction for '$nodeTXRoot->{path}'\n";
		return BTRAM_BIND_BLOCK;
	}

	$rc = max($rc, &tx_umount_descendants($nodeTXRoot));
	return $rc if $rc >= 64;

	my $swap_ok = 1;
	if (defined $mountInfoTXRoot)
	{
		my $subvolOld = $nodeTXRoot->{oldSubvol};
		my $subvolNew = $nodeTXRoot->{newSubvol};
		$swap_ok = &mount_btrfs($mountInfoTXRoot->{mount}, $mountInfoTXRoot->{blkdev}, $subvolNew, $mountInfoTXRoot->{options}, 1);
		unless ($swap_ok)
		{
			warn "Error: remount failed for '$mountInfoTXRoot->{mount}', attempting rollback\n";
			my $rollbackOk = &mount_btrfs($mountInfoTXRoot->{mount}, $mountInfoTXRoot->{blkdev}, $subvolOld, $mountInfoTXRoot->{options}, 0);
			warn "Error: rollback failed for '$mountInfoTXRoot->{mount}'\n" unless $rollbackOk;
			$rc = max($rc, BTRAM_MOUNT_FAILED);
			$rc = max($rc, BTRAM_ROLLBACK_FAILED) unless $rollbackOk;
		}
	}
	else
	{
		my $configEntry = $nodeTXRoot->{cfg};
		die unless defined $configEntry;
		my $rootMount = $configEntry->{root};
		my $blockDevice = $root2bd{$rootMount};
		unless (defined $blockDevice)
		{
			warn "Error: cannot mount '$nodeTXRoot->{path}' because root mount '$rootMount' is not known\n";
			$swap_ok = 0;
			$rc = max($rc, 2);
		}
		else
		{
			$swap_ok = &mount_btrfs($nodeTXRoot->{path}, $blockDevice, $nodeTXRoot->{newSubvol}, {ro => undef}, 0);
			$rc = max($rc, BTRAM_MOUNT_FAILED) unless $swap_ok;
		}
	}

	$rc = max($rc, 1) if $swap_ok;

	$rc = max($rc, &tx_restore_descendants($nodeTXRoot));

	return $rc;
}

sub tx_find_bind_descendant
{
	my ($node) = @_;

	for my $child (values %{$node->{children}})
	{
		my $mountInfo = $child->{oldMount};
		return $mountInfo->{mount} if defined $mountInfo and $mountInfo->{is_bind};
		if (my $bindMountPath = &tx_find_bind_descendant($child))
		{
			return $bindMountPath;
		}
	}
}

sub tx_umount_descendants
{
	my ($node) = @_;
	my $rc = 0;

	for my $child (values %{$node->{children}})
	{
		$rc = max($rc, &tx_umount_descendants($child));

		my $mountInfo = $child->{oldMount};
		next unless defined $mountInfo;

		my $ok = &do_umount($mountInfo->{mount});
		$rc = max($rc, BTRAM_UMOUNT_FAILED) unless $ok;
	}

	return $rc;
}

sub tx_restore_descendants
{
	my ($node) = @_;
	my $rc = 0;

	for my $child (values %{$node->{children}})
	{
		$rc = max($rc, &tx_restore_node($child));
		$rc = max($rc, &tx_restore_descendants($child));
	}

	return $rc;
}

sub tx_restore_node
{
	my ($node) = @_;

	my $mountInfo = $node->{oldMount};
	return 0 unless defined $mountInfo;

	unless (-e -d $mountInfo->{mount})
	{
		warn "Error: not restoring '$mountInfo->{mount}' because mountpoint directory is missing\n";
		return 2;
	}

	if ($mountInfo->{is_bind})
	{
		warn "Error: not restoring bind mount '$mountInfo->{mount}'\n";
		return BTRAM_BIND_BLOCK;
	}

	if ($mountInfo->{fstype} eq 'btrfs' and defined $node->{newSubvol} and defined $node->{oldSubvol} and $node->{newSubvol} ne $node->{oldSubvol})
	{
		my $ok = &mount_btrfs($mountInfo->{mount}, $mountInfo->{blkdev}, $node->{newSubvol}, $mountInfo->{options}, 0);
		return $ok ? 0 : BTRAM_RESTORE_FAILED;
	}

	my $ok = &mount_generic($mountInfo);
	return $ok ? 0 : BTRAM_RESTORE_FAILED;
}

sub do_umount
{
	my ($mountPoint) = @_;

	my @cmdUmount = ('umount');
	push @cmdUmount, '-f' if $mode_force;
	push @cmdUmount, $mountPoint;

	warn "> @cmdUmount\n" if $mode_verbose;

	return 1 unless $mode_run;

	if (system(@cmdUmount))
	{
		warn "Couldn't unmount '$mountPoint'\n";
		return 0;
	}

	return 1;
}

sub mt_find_bind_ancestor
{
	my ($root, $path) = @_;

	return undef unless defined $root and defined $path;

	my @parts = grep { $_ ne '' } split(m{/+}, $path);
	my $node = $root;

	if (defined $node->{oldMount} and $node->{oldMount}->{is_bind})
	{
		return $node->{path};
	}

	for my $part (@parts)
	{
		my $child = $node->{children}->{$part};
		last unless defined $child;
		$node = $child;
		if (defined $node->{oldMount} and $node->{oldMount}->{is_bind})
		{
			return $node->{path};
		}
	}
}

sub mount_btrfs
{
	my ($mountPoint, $blockDevice, $subvol, $opts, $remount) = @_;

	return 0 unless defined $mountPoint and defined $blockDevice and defined $subvol;
	return 0 unless -e -d $mountPoint;

	my @cmdUmount = ('umount');
	push @cmdUmount, '-f' if $mode_force;
	push @cmdUmount, $mountPoint;

	my %o;
	%o = %$opts if defined $opts;
	delete $o{subvol};
	delete $o{subvolid};
	delete $o{bind};
	delete $o{rbind};
	delete $o{rw};
	$o{ro} = undef;

	my @optlist;
	for my $optKey (keys %o)
	{
		push @optlist, defined $o{$optKey} ? "$optKey=$o{$optKey}" : $optKey;
	}
	push @optlist, "subvol=$subvol";

	my @cmdMount = ('mount', '-t', 'btrfs', '-o', join(',', @optlist), $blockDevice, $mountPoint);

	if ($mode_verbose)
	{
		warn "> @cmdUmount\n" if $remount;
		warn "> @cmdMount\n";
	}

	return 1 unless $mode_run;

	if ($remount and system(@cmdUmount))
	{
		warn "Couldn't unmount '$mountPoint'\n";
		return 0;
	}

	if (system(@cmdMount))
	{
		warn "Couldn't mount '$mountPoint'!\n";
		return 0;
	}

	return 1;
}

sub mount_generic
{
	my ($mountInfo) = @_;

	return 0 unless defined $mountInfo;
	return 0 unless -e -d $mountInfo->{mount};

	if ($mountInfo->{is_bind})
	{
		warn "Error: bind mount '$mountInfo->{mount}' is not supported\n";
		return 0;
	}

	my %o;
	%o = %{$mountInfo->{options}} if defined $mountInfo->{options};
	delete $o{bind};
	delete $o{rbind};

	my @optlist;
	for my $optKey (keys %o)
	{
		push @optlist, defined $o{$optKey} ? "$optKey=$o{$optKey}" : $optKey;
	}

	my @cmdMount = ('mount', '-t', $mountInfo->{fstype});
	push @cmdMount, ('-o', join(',', @optlist)) if @optlist;
	push @cmdMount, ($mountInfo->{blkdev}, $mountInfo->{mount});

	warn "> @cmdMount\n" if $mode_verbose;

	return 1 unless $mode_run;

	if (system(@cmdMount))
	{
		warn "Couldn't mount '$mountInfo->{mount}'!\n";
		return 0;
	}

	return 1;
}

sub mt_walk
{
	my ($node, $cb) = @_;

	$cb->($node);

	for my $child (values %{$node->{children}})
	{
		&mt_walk($child, $cb);
	}
}

sub is_ignored_mount_path
{
	my ($path) = @_;

	return undef unless defined $path;

	for my $prefix (@ignore_mount_prefixes)
	{
		return 1 if $path eq $prefix;
		return 1 if $path =~ /^\Q$prefix\E\//;
	}
}

sub sv_info
{
	my ($rootMount, $sv) = @_;

	# TODO list invocation!
	open my $subvolShowHandle, '-|', "btrfs subvolume show '$rootMount/$sv'" or die;

	my $header = <$subvolShowHandle>;
	die unless   defined $header  and  $header eq "$sv\n";

	my %result = ();

	while (<$subvolShowHandle>)
	{
		last if /^\s*Snapshot\(s\):/; # Stop when the snapshot list starts
		die unless /^\s*([^:]*):\s*(.+)$/;
		$result{$1} = $2;
	}

	close $subvolShowHandle;

	return \%result;
}

sub sv_impure
{
	my ($svi) = @_;

	return 'RW' if $svi->{'Flags'} ne 'readonly';
	return undef if $svi->{'Received UUID'} ne '-';
	return 'modified' if $svi->{'Generation'} ne $svi->{'Gen at creation'};
}

sub find_latest
{
	my ($rootMount, $ssdir, $ssnPrefix) = @_;

	die unless $ssnPrefix;

	# See whether there's a newer snapshot
	my $snapshotName;
	while ($_ = glob("$rootMount/$ssdir/$ssnPrefix.*"))
	{
		die unless /^\Q$rootMount\/$ssdir\/$ssnPrefix.\E(\d+(?:_\d+)?)$/;

		my $ssnCandidate = "$ssnPrefix.$1";

		if (my $status = &sv_impure(&sv_info($rootMount, "$ssdir/$ssnCandidate")))
		{
			warn "Warning: ignoring $status subvol '$ssdir/$ssnCandidate\n";
			next;
		}

		$snapshotName = $ssnCandidate if   (not defined $snapshotName)  or  $ssnCandidate gt $snapshotName;
	}

	return "$ssdir/$snapshotName" if defined $snapshotName;
}

sub process_mount
{
	my ($blkdev, $mount, $sv) = @_;

	die unless defined $blkdev and defined $mount;

	if (not defined $sv and $is_root_mount{$mount})
	{
		$bd2root{$blkdev} = $mount;
		$root2bd{$mount} = $blkdev;
		return;
	}

	if (defined $sv)
	{
		# Special handling for root-subvol mounts
		if ($sv eq '')
		{
			$bd2root{$blkdev} = $mount;
			$root2bd{$mount} = $blkdev;
			return;
		}

		$sv =~ s{^/}{};
	}

	# We must have previously processed the root-subvol mount line for this block device (TODO make order-independent)
	my $rootMount = $bd2root{$blkdev};
	unless (defined $rootMount)
	{
		warn "Warning: $blkdev has a subvol at '$mount', but its root subvol is not mounted\n";
		return;
	}

	my $cfg = $config->{$mount};
	$cfg->{done} = 1;

	warn "Warning: mount '$mount' is not mentioned in config\n" unless defined $cfg;

	unless (defined $sv)
	{
		warn "Warning: mount '$mount' has no subvol; was it deleted?\n";

		return unless defined $cfg;

		my ($ssdir, $ssPrefix) = ($cfg->{dir}, $cfg->{prefix});

		my $svNew = &find_latest($rootMount, $ssdir, $ssPrefix);
		return unless   defined $svNew;

		print "Update: '$mount' -> '$rootMount/$svNew'\n";
		return $svNew;
	}

	if (my $status = &sv_impure(&sv_info($rootMount, $sv)))
	{
		print "No change: '$mount' -> $rootMount/$sv ($status)\n" if $mode_verbose;
		return;
	}

	# Snapshots live at least one directory deep
	return unless $sv =~ /^(.+)\/([^,\)]+)/;
	my ($ssdir, $ssnCurr) = ($1, $2);

	# Snapshots are named <prefix> . <number>
	return unless $ssnCurr =~ /^(.+)\.\d+(?:_\d+)?/;
	my $ssPrefix = $1;

	my $svMounted = &sv_info($rootMount, $sv);

	print "No change: '$mount' -> '$rootMount/$sv'\n" if $mode_verbose;

	my $svNew = &find_latest($rootMount, $ssdir, $ssPrefix);

	return unless   defined $svNew  and  $svNew ne $sv;

	print "Update: '$mount' -> '$rootMount/$svNew'\n";
	return $svNew;
}

sub mount
{
	my ($mount, $blkdev, $sv, $remount) = @_;

	my @uc = ('umount', $mount );
	my @mc = ( 'mount', '-o', "ro,subvol=$sv", $blkdev, $mount );

	if ($mode_verbose)
	{
		warn "> @uc\n" if  $mode_verbose and $remount;
		warn "> @mc\n" if  $mode_verbose;
	}

	return undef unless $mode_run;

	if ($remount and system(@uc))
	{
		warn "Couldn't unmount '$mount'\n";
		return 0;
	}

	if (system(@mc))
	{
		warn "Couldn't mount '$mount'!\n";
		return 0;
	}

	return 1;
}
