#!/usr/bin/env perl

use utf8;
use strict;
use warnings;

use Getopt::Lucid qw( :all );
use IPC::Run qw(run);

my @options_spec = (
	Switch(    '--run|-r')->doc('Actually perform [re]mount operations' ),
	Switch('--verbose|-v')->doc('Print analysis details'                ),
	Switch(   '--help|-h')->doc('Print usage (this)'                    ),
);

my $options = Getopt::Lucid->getopt(\@options_spec, {strict => 1})->validate();

usage() and exit(0) if $options->get_help;

STDOUT->autoflush(1);
STDERR->autoflush(1);

my $mode_run     = $options->get_run();
my $mode_verbose = $options->get_verbose();

my @ignore_mount_prefixes = qw(/proc /sys /sysfs /var);

my $config = &get_config('/etc/btram.conf');

my %is_root_mount;
for my $m (keys %$config)
{
	$is_root_mount{$config->{$m}->{root}} = 1;
}

our (%bd2root, %root2bd); # Map between device nodes and root-subvol mounts

open my $h, '<', '/proc/self/mountinfo' or die;

# TODO check that mount points corresponding to config items have snapshots mounted that conform to config's pattern

my $mount_tree = &mt_new('/', '/');

while (<$h>)
{
	next unless my $m = &parse_mountinfo($_);
	next if &is_ignored_mount_path($m->{mount});
	&mt_insert($mount_tree, $m->{mount}, $m);
}

close $h;

&mt_walk($mount_tree, sub {
	my ($n) = @_;
	my $m = $n->{oldMount};
	return unless defined $m and $m->{fstype} eq 'btrfs';

	my ($blkdev, $mount, $sv) = ($m->{blkdev}, $m->{mount}, $n->{oldSubvol});

	if (defined $sv)
	{
		return unless $sv eq '';
	}
	else
	{
		return unless $is_root_mount{$mount};
	}

	$bd2root{$blkdev} = $mount;
	$root2bd{$mount} = $blkdev;
});

&mt_walk($mount_tree, sub {
	my ($n) = @_;
	my $m = $n->{oldMount};
	return unless defined $m and $m->{fstype} eq 'btrfs';

	my ($blkdev, $mount) = ($m->{blkdev}, $m->{mount});
	my $svNew = &process_mount($blkdev, $mount, $n->{oldSubvol});
	if ($svNew)
	{
		$n->{newSubvol} = $svNew;
		&mount($mount, $blkdev, $svNew, 1);
	}
});

while (my ($mount, $cfg) = each (%$config))
{
	next if $cfg->{done};

	print "Mount [fresh]: $mount\n";

	# We must have previously processed the root-subvol mount line for this block device (TODO make order-independent)
	my $rootMount = $cfg->{root};
	die unless defined $rootMount;

	# we need to do a value->key lookup on %rootMounts to get blkdev from $rootMount
	my $svNew = &find_latest($rootMount, $cfg->{dir}, $cfg->{prefix});

	warn "Warning: '$mount' has no snapshots '$cfg->{dir}/$cfg->{prefix}.*'\n" unless defined $svNew;

	&mount($mount, $root2bd{$rootMount}, $svNew, 0);
}

exit 0;

################################################################################

sub usage
{
  print "BTRam v1.0, copyright © 2023 Luxagen\n\n";

  print $options->usage();

  print <<EOF

https://github.com/luxagen/btram

EOF
}

sub get_config
{
	my ($file) = @_;

	my %result;

	open my $h, '<', $file or die "Missing/inaccessible config; nothing to do\n";

	while (<$h>)
	{
		next if /^\n$/;
		next if /^\s*#/;


		die "Error: config line is malformed\n" unless /^([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t]+)\n$/;
		die "Error: config line is missing field(s)\n" unless  $1 and $2 and $3 and $4;

		die "Error: subvol mount point '$1' missing\n" unless -e -d $1;
		die "Error: volume mount point '$2' missing\n" unless -e -d $2;
		die "Error: snapshot directory '$2/$3' missing\n" unless -e -d "$2/$3";

		$result{$1}->{root  } = $2;
		$result{$1}->{dir   } = $3;
		$result{$1}->{prefix} = $4;

		die "Error: subvol mount point '$1' is under an ignored mount tree\n" if &is_ignored_mount_path($1);
		die "Error: volume mount point '$2' is under an ignored mount tree\n" if &is_ignored_mount_path($2);
	}

	close $h;

	return \%result;
}

sub parse_mount
{
	return undef unless /^([^\s]+)\s+on\s+([^\s]+)\s+type\s+(.+)\s+\((.+)\)$/;

	my $result =
	{
		blkdev => $1,
		mount => $2,
		fstype => $3,
		options => {},
		done => 0,
	};

	for (split(/,/, $4))
	{
		next unless /^([^=]+)(?:=(.+))?$/;

		$result->{options}->{$1} = $2;
	}

	return $result;
}

sub parse_mountinfo
{
	my ($line) = @_;

	chomp $line;

	my ($left, $right) = split(/\s-\s/, $line, 2);
	return undef unless defined $right;

	my @l = split(/\s+/, $left);
	return undef unless @l >= 6;

	my ($root, $mount, $opts) = @l[3,4,5];
	$root  = &unescape_mountinfo($root);
	$mount = &unescape_mountinfo($mount);

	my @r = split(/\s+/, $right, 3);
	return undef unless @r == 3;
	my ($fstype, $source, $superopts) = @r;
	$source = &unescape_mountinfo($source);

	my $result =
	{
		blkdev => $source,
		mount => $mount,
		fstype => $fstype,
		options => {},
		mnt_opts => {},
		super_opts => {},
		root => $root,
		is_bind => 0,
		done => 0,
	};

	&parse_mount_opts($result->{mnt_opts}, $opts);
	&parse_mount_opts($result->{super_opts}, $superopts);

	%{$result->{options}} = (%{$result->{mnt_opts}}, %{$result->{super_opts}});

	$result->{is_bind} = 1 if exists $result->{mnt_opts}->{bind} or exists $result->{mnt_opts}->{rbind};

	return $result;
}

sub parse_mount_opts
{
	my ($out, $s) = @_;

	return unless defined $out and defined $s;

	for (split(/,/, $s))
	{
		next unless /^([^=]+)(?:=(.+))?$/;
		$out->{$1} = $2;
	}
}

sub unescape_mountinfo
{
	my ($s) = @_;

	return undef unless defined $s;

	$s =~ s/\\([0-7]{3})/chr(oct($1))/ge;
	return $s;
}

sub mt_new
{
	my ($name, $path) = @_;

	return
	{
		name => $name,
		path => $path,
		children => {},
	};
}

sub mt_insert
{
	my ($root, $path, $m) = @_;

	die unless defined $root and defined $path and defined $m;

	my @parts = grep { $_ ne '' } split(m{/+}, $path);

	my $n = $root;
	my $p = '';
 
	for my $part (@parts)
	{
		$p .= "/$part";

		my $c = $n->{children}->{$part};
		unless (defined $c)
		{
			$c = &mt_new($part, $p);
			$n->{children}->{$part} = $c;
		}

		$n = $c;
	}

	die "Duplicate mount point '$path'\n" if defined $n->{oldMount};

	$n->{oldMount} = $m;

	my $sv = $m->{options}->{subvol};
	$sv = '' if defined $sv and $sv eq '/';
	$sv =~ s{^/}{} if defined $sv;
	$n->{oldSubvol} = $sv;
}

sub mt_walk
{
	my ($n, $cb) = @_;

	$cb->($n);

	for my $c (values %{$n->{children}})
	{
		&mt_walk($c, $cb);
	}
}

sub is_ignored_mount_path
{
	my ($path) = @_;

	return undef unless defined $path;

	for my $p (@ignore_mount_prefixes)
	{
		return 1 if $path eq $p;
		return 1 if $path =~ /^\Q$p\E\//;
	}
}

sub sv_info
{
	my ($rootMount, $sv) = @_;

	# TODO list invocation!
	open my $h, '-|', "btrfs subvolume show '$rootMount/$sv'" or die;

	my $header = <$h>;
	die unless   defined $header  and  $header eq "$sv\n";

	my %r=();

	while (<$h>)
	{
		last if /^\s*Snapshot\(s\):/; # Stop when the snapshot list starts
		die unless /^\s*([^:]*):\s*(.+)$/;
		$r{$1} = $2;
	}

	close $h;

	return \%r;
}

sub sv_impure
{
	my ($svi) = @_;

	return 'RW' if $svi->{'Flags'} ne 'readonly';
	return undef if $svi->{'Received UUID'} ne '-';
	return 'modified' if $svi->{'Generation'} ne $svi->{'Gen at creation'};
}

sub find_latest
{
	my ($rootMount, $ssdir, $ssnPrefix) = @_;

	die unless $ssnPrefix;

	# See whether there's a newer snapshot
	my $ssn;
	while ($_ = glob("$rootMount/$ssdir/$ssnPrefix.*"))
	{
		die unless /^\Q$rootMount\/$ssdir\/$ssnPrefix.\E(\d+(?:_\d+)?)$/;

		my $ssnCandidate = "$ssnPrefix.$1";

		if (my $status = &sv_impure(&sv_info($rootMount, "$ssdir/$ssnCandidate")))
		{
			warn "Warning: ignoring $status subvol '$ssdir/$ssnCandidate\n";
			next;
		}

		$ssn = $ssnCandidate if   (not defined $ssn)  or  $ssnCandidate gt $ssn;
	}

	return "$ssdir/$ssn" if defined $ssn;
}

sub process_mount
{
	my ($blkdev, $mount, $sv) = @_;

	die unless defined $blkdev and defined $mount;

	if (not defined $sv and $is_root_mount{$mount})
	{
		$bd2root{$blkdev} = $mount;
		$root2bd{$mount} = $blkdev;
		return;
	}

	if (defined $sv)
	{
		# Special handling for root-subvol mounts
		if ($sv eq '')
		{
			$bd2root{$blkdev} = $mount;
			$root2bd{$mount} = $blkdev;
			return;
		}

		$sv =~ s{^/}{};
	}

	# We must have previously processed the root-subvol mount line for this block device (TODO make order-independent)
	my $rootMount = $bd2root{$blkdev};
	unless (defined $rootMount)
	{
		warn "Warning: $blkdev has a subvol at '$mount', but its root subvol is not mounted\n";
		return;
	}

	my $cfg = $config->{$mount};
	$cfg->{done} = 1;

	warn "Warning: mount '$mount' is not mentioned in config\n" unless defined $cfg;

	unless (defined $sv)
	{
		warn "Warning: mount '$mount' has no subvol; was it deleted?\n";

		return unless defined $cfg;

		my ($ssdir, $ssPrefix) = ($cfg->{dir}, $cfg->{prefix});

		my $svNew = &find_latest($rootMount, $ssdir, $ssPrefix);
		return unless   defined $svNew;

		print "'$mount': $rootMount/$svNew replaces <none>\n";
		return $svNew;
	}

	if (my $status = &sv_impure(&sv_info($rootMount, $sv)))
	{
		print "Mount [skipped - $status]: '$mount' -> $rootMount/$sv\n" if $mode_verbose;
		return;
	}

	# Snapshots live at least one directory deep
	return unless $sv =~ /^(.+)\/([^,\)]+)/;
	my ($ssdir, $ssnCurr) = ($1, $2);

	# Snapshots are named <prefix> . <number>
	return unless $ssnCurr =~ /^(.+)\.\d+(?:_\d+)?/;
	my $ssPrefix = $1;

	my $svMounted = &sv_info($rootMount, $sv);

	print "Mount [candidate]: '$mount' -> '$rootMount/$sv'\n" if $mode_verbose;

	my $svNew = &find_latest($rootMount, $ssdir, $ssPrefix);

	return unless   defined $svNew  and  $svNew ne $sv;

	print "'$mount': '$rootMount/$svNew' replaces '$rootMount/$sv'\n";
	return $svNew;
}

sub mount
{
	my ($mount, $blkdev, $sv, $remount) = @_;

	my @uc = ('umount', $mount );
	my @mc = ( 'mount', '-o', "ro,subvol=$sv", $blkdev, $mount );

	if ($mode_verbose)
	{
		warn "> @uc\n" if  $mode_verbose and $remount;
		warn "> @mc\n" if  $mode_verbose;
	}

	return undef unless $mode_run;

	if ($remount and system(@uc))
	{
		warn "Couldn't unmount '$mount'\n";
		return 0;
	}

	if (system(@mc))
	{
		warn "Couldn't mount '$mount'!\n";
		return 0;
	}

	return 1;
}
