#!/usr/bin/env perl

use utf8;
use strict;
use warnings;

use Getopt::Lucid qw( :all );
use IPC::Run qw(run);

my @options_spec = (
	Switch(    '--run|-r')->doc('Actually perform [re]mount operations' ),
	Switch('--verbose|-v')->doc('Print analysis details'                ),
	Switch(  '--force|-f')->doc('Pass -f to umount'                     ),
	Switch(   '--help|-h')->doc('Print usage (this)'                    ),
);

my $options = Getopt::Lucid->getopt(\@options_spec, {strict => 1})->validate();

usage() and exit(0) if $options->get_help;

STDOUT->autoflush(1);
STDERR->autoflush(1);

my $mode_run     = $options->get_run();
my $mode_verbose = $options->get_verbose();
my $mode_force   = $options->get_force();

my @ignore_mount_prefixes = qw(/proc /sys /sysfs /var);

my $config = &get_config('/etc/btram.conf');

my %is_root_mount;
for my $m (keys %$config)
{
	$is_root_mount{$config->{$m}->{root}} = 1;
}

our (%bd2root, %root2bd); # Map between device nodes and root-subvol mounts

open my $h, '<', '/proc/self/mountinfo' or die;

# TODO check that mount points corresponding to config items have snapshots mounted that conform to config's pattern

my $mount_tree = &mt_new('/', '/');

while (<$h>)
{
	next unless my $m = &parse_mountinfo($_);
	next if &is_ignored_mount_path($m->{mount});
	&mt_insert($mount_tree, $m->{mount}, $m);
}

close $h;

&mt_walk($mount_tree, sub {
	my ($n) = @_;
	my $m = $n->{oldMount};
	return unless defined $m and $m->{fstype} eq 'btrfs';

	my ($blkdev, $mount, $sv) = ($m->{blkdev}, $m->{mount}, $n->{oldSubvol});

	if (defined $sv)
	{
		return unless $sv eq '';
	}
	else
	{
		return unless $is_root_mount{$mount};
	}

	$bd2root{$blkdev} = $mount;
	$root2bd{$mount} = $blkdev;
});

for my $mount (keys %$config)
{
	my $cfg = $config->{$mount};
	next unless defined $cfg;

	my $n = &mt_get_node($mount_tree, $mount, 1);
	if (defined $n)
	{
		$n->{cfg} = $cfg;
	}
}

&mt_walk($mount_tree, sub {
	my ($n) = @_;
	return unless defined $n->{cfg};

	my $cfg = $n->{cfg};
	my $m = $n->{oldMount};

	my $rootMount = $cfg->{root};
	die unless defined $rootMount;

	if (defined $m)
	{
		return unless $m->{fstype} eq 'btrfs';

		my ($blkdev, $mount, $sv) = ($m->{blkdev}, $m->{mount}, $n->{oldSubvol});
		my $svNew = &process_mount($blkdev, $mount, $sv);
		$n->{newSubvol} = $svNew if defined $svNew;
	}
	else
	{
		my $svNew = &find_latest($rootMount, $cfg->{dir}, $cfg->{prefix});
		warn "Warning: '$n->{path}' has no snapshots '$cfg->{dir}/$cfg->{prefix}.*'\n" unless defined $svNew;
		$n->{newSubvol} = $svNew if defined $svNew;
	}
});

my @swap_roots;
&mt_collect_swap_roots($mount_tree, 0, \@swap_roots);

for my $r (@swap_roots)
{
	&do_transaction($r);
}

exit 0;

################################################################################

sub usage
{
  print "BTRam v1.0, copyright © 2023 Luxagen\n\n";

  print $options->usage();

  print <<EOF

https://github.com/luxagen/btram

EOF
}

sub get_config
{
	my ($file) = @_;

	my %result;

	open my $h, '<', $file or die "Missing/inaccessible config; nothing to do\n";

	while (<$h>)
	{
		next if /^\n$/;
		next if /^\s*#/;


		die "Error: config line is malformed\n" unless /^([^\t]+)\t+([^\t]+)\t+([^\t]+)\t+([^\t]+)\n$/;
		die "Error: config line is missing field(s)\n" unless  $1 and $2 and $3 and $4;

		die "Error: subvol mount point '$1' missing\n" unless -e -d $1;
		die "Error: volume mount point '$2' missing\n" unless -e -d $2;
		die "Error: snapshot directory '$2/$3' missing\n" unless -e -d "$2/$3";

		$result{$1}->{root  } = $2;
		$result{$1}->{dir   } = $3;
		$result{$1}->{prefix} = $4;

		die "Error: subvol mount point '$1' is under an ignored mount tree\n" if &is_ignored_mount_path($1);
		die "Error: volume mount point '$2' is under an ignored mount tree\n" if &is_ignored_mount_path($2);
	}

	close $h;

	return \%result;
}

sub parse_mountinfo
{
	my ($line) = @_;

	chomp $line;

	my ($left, $right) = split(/\s-\s/, $line, 2);
	return undef unless defined $right;

	my @l = split(/\s+/, $left);
	return undef unless @l >= 6;

	my ($root, $mount, $opts) = @l[3,4,5];
	$root  = &unescape_mountinfo($root);
	$mount = &unescape_mountinfo($mount);

	my @r = split(/\s+/, $right, 3);
	return undef unless @r == 3;
	my ($fstype, $source, $superopts) = @r;
	$source = &unescape_mountinfo($source);

	my $result =
	{
		blkdev => $source,
		mount => $mount,
		fstype => $fstype,
		options => {},
		mnt_opts => {},
		super_opts => {},
		root => $root,
		is_bind => 0,
		done => 0,
	};

	&parse_mount_opts($result->{mnt_opts}, $opts);
	&parse_mount_opts($result->{super_opts}, $superopts);

	%{$result->{options}} = (%{$result->{mnt_opts}}, %{$result->{super_opts}});

	$result->{is_bind} = 1 if exists $result->{mnt_opts}->{bind} or exists $result->{mnt_opts}->{rbind};

	return $result;
}

sub parse_mount_opts
{
	my ($out, $s) = @_;

	return unless defined $out and defined $s;

	for (split(/,/, $s))
	{
		next unless /^([^=]+)(?:=(.+))?$/;
		$out->{$1} = $2;
	}
}

sub unescape_mountinfo
{
	my ($s) = @_;

	return undef unless defined $s;

	$s =~ s/\\([0-7]{3})/chr(oct($1))/ge;
	return $s;
}

sub mt_new
{
	my ($name, $path) = @_;

	return
	{
		name => $name,
		path => $path,
		children => {},
	};
}

sub mt_insert
{
	my ($root, $path, $m) = @_;

	die unless defined $root and defined $path and defined $m;

	my @parts = grep { $_ ne '' } split(m{/+}, $path);

	my $n = $root;
	my $p = '';
 
	for my $part (@parts)
	{
		$p .= "/$part";

		my $c = $n->{children}->{$part};
		unless (defined $c)
		{
			$c = &mt_new($part, $p);
			$n->{children}->{$part} = $c;
		}

		$n = $c;
	}

	die "Duplicate mount point '$path'\n" if defined $n->{oldMount};

	$n->{oldMount} = $m;

	my $sv = $m->{options}->{subvol};
	$sv = '' if defined $sv and $sv eq '/';
	$sv =~ s{^/}{} if defined $sv;
	$n->{oldSubvol} = $sv;
}

sub mt_get_node
{
	my ($root, $path, $create) = @_;

	die unless defined $root and defined $path;

	my @parts = grep { $_ ne '' } split(m{/+}, $path);

	my $n = $root;
	my $p = '';

	if ($create and defined $n->{oldMount} and $n->{oldMount}->{is_bind})
	{
		warn "Error: refusing to create node for '$path' under bind mount '$n->{path}'\n";
		return undef;
	}

	for my $part (@parts)
	{
		$p .= "/$part";
		my $c = $n->{children}->{$part};
		unless (defined $c)
		{
			return undef unless $create;
			$c = &mt_new($part, $p);
			$n->{children}->{$part} = $c;
		}
		$n = $c;

		if ($create and defined $n->{oldMount} and $n->{oldMount}->{is_bind})
		{
			warn "Error: refusing to create node for '$path' under bind mount '$n->{path}'\n";
			return undef;
		}
	}

	return $n;
}

sub mt_collect_swap_roots
{
	my ($n, $ancestor_swap, $out) = @_;

	my $m = $n->{oldMount};

	my $swap = 0;
	if (defined $n->{newSubvol})
	{
		if (defined $m)
		{
			$swap = 1 if $m->{fstype} eq 'btrfs' and defined $n->{oldSubvol} and $n->{newSubvol} ne $n->{oldSubvol};
		}
		else
		{
			$swap = 1;
		}
	}

	push @$out, $n if $swap and not $ancestor_swap;

	for my $c (values %{$n->{children}})
	{
		&mt_collect_swap_roots($c, ($ancestor_swap || $swap), $out);
	}
}

sub do_transaction
{
	my ($r) = @_;

	if (&mt_has_bind_ancestor($mount_tree, $r->{path}))
	{
		warn "Error: bind mount blocks remount transaction for '$r->{path}'\n";
		return 0;
	}

	my $rm = $r->{oldMount};

	if (&tx_has_bind_descendant($r))
	{
		warn "Error: bind mount blocks remount transaction for '$r->{path}'\n";
		return 0;
	}

	return 0 unless &tx_umount_descendants($r);

	my $swap_ok = 1;
	if (defined $rm)
	{
		my $old = $r->{oldSubvol};
		my $new = $r->{newSubvol};
		$swap_ok = &mount_btrfs($rm->{mount}, $rm->{blkdev}, $new, $rm->{options}, 1);
		unless ($swap_ok)
		{
			warn "Error: remount failed for '$rm->{mount}', attempting rollback\n";
			my $rb = &mount_btrfs($rm->{mount}, $rm->{blkdev}, $old, $rm->{options}, 0);
			warn "Error: rollback failed for '$rm->{mount}'\n" unless $rb;
		}
	}
	else
	{
		my $cfg = $r->{cfg};
		die unless defined $cfg;
		my $rootMount = $cfg->{root};
		my $blkdev = $root2bd{$rootMount};
		unless (defined $blkdev)
		{
			warn "Error: cannot mount '$r->{path}' because root mount '$rootMount' is not known\n";
			$swap_ok = 0;
		}
		else
		{
			$swap_ok = &mount_btrfs($r->{path}, $blkdev, $r->{newSubvol}, {ro => undef}, 0);
		}
	}


	&tx_restore_descendants($r);

	return $swap_ok;
}

sub tx_has_bind_descendant
{
	my ($n) = @_;

	for my $c (values %{$n->{children}})
	{
		my $m = $c->{oldMount};
		return 1 if defined $m and $m->{is_bind};
		return 1 if &tx_has_bind_descendant($c);
	}
}

sub tx_umount_descendants
{
	my ($n) = @_;

	for my $c (values %{$n->{children}})
	{
		return 0 unless &tx_umount_descendants($c);
	}

	my $m = $n->{oldMount};
	return 1 unless defined $m;

	return &do_umount($m->{mount});
}

sub tx_restore_descendants
{
	my ($n) = @_;

	my $m = $n->{oldMount};
	if (defined $m)
	{
		unless (-e -d $m->{mount})
		{
			warn "Error: not restoring '$m->{mount}' because mountpoint directory is missing\n";
			return;
		}

		if ($m->{is_bind})
		{
			warn "Error: not restoring bind mount '$m->{mount}'\n";
			return;
		}

		if ($m->{fstype} eq 'btrfs' and defined $n->{newSubvol} and defined $n->{oldSubvol} and $n->{newSubvol} ne $n->{oldSubvol})
		{
			&mount_btrfs($m->{mount}, $m->{blkdev}, $n->{newSubvol}, $m->{options}, 0);
		}
		else
		{
			&mount_generic($m);
		}
	}

	for my $c (values %{$n->{children}})
	{
		&tx_restore_descendants($c);
	}
}

sub do_umount
{
	my ($mount) = @_;

	my @uc = ('umount');
	push @uc, '-f' if $mode_force;
	push @uc, $mount;

	warn "> @uc\n" if $mode_verbose;

	return 1 unless $mode_run;

	if (system(@uc))
	{
		warn "Couldn't unmount '$mount'\n";
		return 0;
	}

	return 1;
}

sub mt_has_bind_ancestor
{
	my ($root, $path) = @_;

	return undef unless defined $root and defined $path;

	my @parts = grep { $_ ne '' } split(m{/+}, $path);
	my $n = $root;

	if (defined $n->{oldMount} and $n->{oldMount}->{is_bind})
	{
		return 1;
	}

	for my $part (@parts)
	{
		my $c = $n->{children}->{$part};
		last unless defined $c;
		$n = $c;
		if (defined $n->{oldMount} and $n->{oldMount}->{is_bind})
		{
			return 1;
		}
	}
}

sub mount_btrfs
{
	my ($mount, $blkdev, $sv, $opts, $remount) = @_;

	return 0 unless defined $mount and defined $blkdev and defined $sv;
	return 0 unless -e -d $mount;

	my @uc = ('umount');
	push @uc, '-f' if $mode_force;
	push @uc, $mount;

	my %o;
	%o = %$opts if defined $opts;
	delete $o{subvol};
	delete $o{subvolid};
	delete $o{bind};
	delete $o{rbind};
	delete $o{rw};
	$o{ro} = undef;

	my @optlist;
	for my $k (keys %o)
	{
		push @optlist, defined $o{$k} ? "$k=$o{$k}" : $k;
	}
	push @optlist, "subvol=$sv";

	my @mc = ('mount', '-t', 'btrfs', '-o', join(',', @optlist), $blkdev, $mount);

	if ($mode_verbose)
	{
		warn "> @uc\n" if $remount;
		warn "> @mc\n";
	}

	return 1 unless $mode_run;

	if ($remount and system(@uc))
	{
		warn "Couldn't unmount '$mount'\n";
		return 0;
	}

	if (system(@mc))
	{
		warn "Couldn't mount '$mount'!\n";
		return 0;
	}

	return 1;
}

sub mount_generic
{
	my ($m) = @_;

	return 0 unless defined $m;
	return 0 unless -e -d $m->{mount};

	if ($m->{is_bind})
	{
		warn "Error: bind mount '$m->{mount}' is not supported\n";
		return 0;
	}

	my %o;
	%o = %{$m->{options}} if defined $m->{options};
	delete $o{bind};
	delete $o{rbind};

	my @optlist;
	for my $k (keys %o)
	{
		push @optlist, defined $o{$k} ? "$k=$o{$k}" : $k;
	}

	my @mc = ('mount', '-t', $m->{fstype});
	push @mc, ('-o', join(',', @optlist)) if @optlist;
	push @mc, ($m->{blkdev}, $m->{mount});

	warn "> @mc\n" if $mode_verbose;

	return 1 unless $mode_run;

	if (system(@mc))
	{
		warn "Couldn't mount '$m->{mount}'!\n";
		return 0;
	}

	return 1;
}

sub mt_walk
{
	my ($n, $cb) = @_;

	$cb->($n);

	for my $c (values %{$n->{children}})
	{
		&mt_walk($c, $cb);
	}
}

sub is_ignored_mount_path
{
	my ($path) = @_;

	return undef unless defined $path;

	for my $p (@ignore_mount_prefixes)
	{
		return 1 if $path eq $p;
		return 1 if $path =~ /^\Q$p\E\//;
	}
}

sub sv_info
{
	my ($rootMount, $sv) = @_;

	# TODO list invocation!
	open my $h, '-|', "btrfs subvolume show '$rootMount/$sv'" or die;

	my $header = <$h>;
	die unless   defined $header  and  $header eq "$sv\n";

	my %r=();

	while (<$h>)
	{
		last if /^\s*Snapshot\(s\):/; # Stop when the snapshot list starts
		die unless /^\s*([^:]*):\s*(.+)$/;
		$r{$1} = $2;
	}

	close $h;

	return \%r;
}

sub sv_impure
{
	my ($svi) = @_;

	return 'RW' if $svi->{'Flags'} ne 'readonly';
	return undef if $svi->{'Received UUID'} ne '-';
	return 'modified' if $svi->{'Generation'} ne $svi->{'Gen at creation'};
}

sub find_latest
{
	my ($rootMount, $ssdir, $ssnPrefix) = @_;

	die unless $ssnPrefix;

	# See whether there's a newer snapshot
	my $ssn;
	while ($_ = glob("$rootMount/$ssdir/$ssnPrefix.*"))
	{
		die unless /^\Q$rootMount\/$ssdir\/$ssnPrefix.\E(\d+(?:_\d+)?)$/;

		my $ssnCandidate = "$ssnPrefix.$1";

		if (my $status = &sv_impure(&sv_info($rootMount, "$ssdir/$ssnCandidate")))
		{
			warn "Warning: ignoring $status subvol '$ssdir/$ssnCandidate\n";
			next;
		}

		$ssn = $ssnCandidate if   (not defined $ssn)  or  $ssnCandidate gt $ssn;
	}

	return "$ssdir/$ssn" if defined $ssn;
}

sub process_mount
{
	my ($blkdev, $mount, $sv) = @_;

	die unless defined $blkdev and defined $mount;

	if (not defined $sv and $is_root_mount{$mount})
	{
		$bd2root{$blkdev} = $mount;
		$root2bd{$mount} = $blkdev;
		return;
	}

	if (defined $sv)
	{
		# Special handling for root-subvol mounts
		if ($sv eq '')
		{
			$bd2root{$blkdev} = $mount;
			$root2bd{$mount} = $blkdev;
			return;
		}

		$sv =~ s{^/}{};
	}

	# We must have previously processed the root-subvol mount line for this block device (TODO make order-independent)
	my $rootMount = $bd2root{$blkdev};
	unless (defined $rootMount)
	{
		warn "Warning: $blkdev has a subvol at '$mount', but its root subvol is not mounted\n";
		return;
	}

	my $cfg = $config->{$mount};
	$cfg->{done} = 1;

	warn "Warning: mount '$mount' is not mentioned in config\n" unless defined $cfg;

	unless (defined $sv)
	{
		warn "Warning: mount '$mount' has no subvol; was it deleted?\n";

		return unless defined $cfg;

		my ($ssdir, $ssPrefix) = ($cfg->{dir}, $cfg->{prefix});

		my $svNew = &find_latest($rootMount, $ssdir, $ssPrefix);
		return unless   defined $svNew;

		print "'$mount': $rootMount/$svNew replaces <none>\n";
		return $svNew;
	}

	if (my $status = &sv_impure(&sv_info($rootMount, $sv)))
	{
		print "Mount [skipped - $status]: '$mount' -> $rootMount/$sv\n" if $mode_verbose;
		return;
	}

	# Snapshots live at least one directory deep
	return unless $sv =~ /^(.+)\/([^,\)]+)/;
	my ($ssdir, $ssnCurr) = ($1, $2);

	# Snapshots are named <prefix> . <number>
	return unless $ssnCurr =~ /^(.+)\.\d+(?:_\d+)?/;
	my $ssPrefix = $1;

	my $svMounted = &sv_info($rootMount, $sv);

	print "Mount [candidate]: '$mount' -> '$rootMount/$sv'\n" if $mode_verbose;

	my $svNew = &find_latest($rootMount, $ssdir, $ssPrefix);

	return unless   defined $svNew  and  $svNew ne $sv;

	print "'$mount': '$rootMount/$svNew' replaces '$rootMount/$sv'\n";
	return $svNew;
}

sub mount
{
	my ($mount, $blkdev, $sv, $remount) = @_;

	my @uc = ('umount', $mount );
	my @mc = ( 'mount', '-o', "ro,subvol=$sv", $blkdev, $mount );

	if ($mode_verbose)
	{
		warn "> @uc\n" if  $mode_verbose and $remount;
		warn "> @mc\n" if  $mode_verbose;
	}

	return undef unless $mode_run;

	if ($remount and system(@uc))
	{
		warn "Couldn't unmount '$mount'\n";
		return 0;
	}

	if (system(@mc))
	{
		warn "Couldn't mount '$mount'!\n";
		return 0;
	}

	return 1;
}
